### ISSUE TITLE
YTMainAppControlsOverlayView @property YTPlayerViewController no longer exists on newer YouTube versions

### ISSUE THREAD

**Issue by bhackel** [aricloverEXTRA/YouTimeStamp#1]
This is related to the button placed at the top of the video player. It does not affect buttons placed at the bottom. This also affects my tweak YouLoop.

It seems that enabling iSponsorBlock changes some A/B flags (probably something to do with modularPlayerBar) to keep YTPlayerViewController a property of the YTMainAppControlsOverlayView class. However, disabling iSponsorBlock causes it to disappear. This scenario is likely to happen when using YouTube Plus sponsorblock instead.

An alternate route is to access the superview of YTMainAppControlsOverlayView, and cast it to the right type

`YTMainAppVideoPlayerOverlayView *mainOverlayView = (YTMainAppVideoPlayerOverlayView *)self.superview;`

Then you can access this view's controller using a UIView property, and casting it to the right type

`YTMainAppVideoPlayerOverlayViewController *mainOverlayController = (YTMainAppVideoPlayerOverlayViewController *)mainOverlayView.viewDelegate;`

Then, the code sequence follows the code in the bottom section button. We can directly access the right controller

`YTPlayerViewController *playerViewController = mainOverlayController.parentViewController;`

I will test this in my tweak and let you know

**Comment by bhackel** [comment]
My implementation was a little different. I would suggest looking at my two latest commits: https://github.com/bhackel/YouLoop/commits/main/

**Comment by aricloverEXTRA** [comment]
Is this backwards compatible for old versions? (including iSponsorBlock being disabled) I’ll definitely update it to be similar to YouLoop.

**Comment by bhackel** [comment]
I can confirm that it works when iSponsorBlock is both on and off. I think that means it should be fine for older versions

**Comment by aricloverEXTRA** [comment]
Fixed in **YouTimeStamp v1.0.1**
